// This file is part of AsmJit project <https://asmjit.com>
//
// See <asmjit/core.h> or LICENSE.md for license and copyright information
// SPDX-License-Identifier: Zlib

// Generated by tools/ppc_instgen.py - do not edit manually.

#ifndef ASMJIT_PPC_PPCEMITTER_H_INCLUDED
#define ASMJIT_PPC_PPCEMITTER_H_INCLUDED

#include <asmjit/core/emitter.h>
#include <asmjit/ppc/ppcassembler.h>
#include <asmjit/ppc/ppcinst.h>

ASMJIT_BEGIN_SUB_NAMESPACE(ppc)

//! Instruction emitter methods shared by the PPC64 compiler.
//!
//! The method set mirrors the instructions supported by the assembler's
//! generic `_emit()` path, so everything emitted here can be serialized.
template<typename This>
struct EmitterExplicitT {
  //! \cond
  ASMJIT_ATTRIBUTE_NO_SANITIZE_UNDEF ASMJIT_INLINE_NODEBUG This* _emitter() noexcept { return static_cast<This*>(this); }
  ASMJIT_ATTRIBUTE_NO_SANITIZE_UNDEF ASMJIT_INLINE_NODEBUG const This* _emitter() const noexcept { return static_cast<const This*>(this); }
  //! \endcond

  //! \name Instruction Emission
  //! \{

  inline Error li(const Gp& rt, const Imm& simm) { return _emitter()->_emitI(Inst::kIdLi, rt, simm); }
  inline Error addi(const Gp& rt, const Gp& ra, const Imm& simm) { return _emitter()->_emitI(Inst::kIdAddi, rt, ra, simm); }
  inline Error addis(const Gp& rt, const Gp& ra, const Imm& simm) { return _emitter()->_emitI(Inst::kIdAddis, rt, ra, simm); }
  inline Error ori(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdOri, ra, rs, uimm); }
  inline Error oris(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdOris, ra, rs, uimm); }
  inline Error sldi(const Gp& ra, const Gp& rs, const Imm& sh) { return _emitter()->_emitI(Inst::kIdSldi, ra, rs, sh); }
  inline Error add(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAdd, rt, ra, rb); }
  inline Error addc(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAddc, rt, ra, rb); }
  inline Error addze(const Gp& rt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdAddze, rt, ra); }
  inline Error addme(const Gp& rt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdAddme, rt, ra); }
  inline Error subf(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSubf, rt, ra, rb); }
  inline Error subfc(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSubfc, rt, ra, rb); }
  inline Error subfze(const Gp& rt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdSubfze, rt, ra); }
  inline Error subfme(const Gp& rt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdSubfme, rt, ra); }
  inline Error neg(const Gp& rt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdNeg, rt, ra); }
  inline Error and_(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAnd_, ra, rs, rb); }
  inline Error andc(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAndc, ra, rs, rb); }
  inline Error or_(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdOr_, ra, rs, rb); }
  inline Error orc(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdOrc, ra, rs, rb); }
  inline Error xor_(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdXor_, ra, rs, rb); }
  inline Error nand(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdNand, ra, rs, rb); }
  inline Error nor(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdNor, ra, rs, rb); }
  inline Error eqv(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdEqv, ra, rs, rb); }
  inline Error sld(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSld, ra, rs, rb); }
  inline Error srd(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSrd, ra, rs, rb); }
  inline Error srad(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSrad, ra, rs, rb); }
  inline Error slw(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSlw, ra, rs, rb); }
  inline Error srw(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSrw, ra, rs, rb); }
  inline Error sraw(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSraw, ra, rs, rb); }
  inline Error extsw(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdExtsw, ra, rs); }
  inline Error extswsli(const Gp& ra, const Gp& rs, const Imm& sh) { return _emitter()->_emitI(Inst::kIdExtswsli, ra, rs, sh); }
  inline Error addic(const Gp& rt, const Gp& ra, const Imm& simm) { return _emitter()->_emitI(Inst::kIdAddic, rt, ra, simm); }
  inline Error subfic(const Gp& rt, const Gp& ra, const Imm& simm) { return _emitter()->_emitI(Inst::kIdSubfic, rt, ra, simm); }
  inline Error adde(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAdde, rt, ra, rb); }
  inline Error subfe(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdSubfe, rt, ra, rb); }
  inline Error addex(const Gp& rt, const Gp& ra, const Gp& rb, const Imm& cy) { return _emitter()->_emitI(Inst::kIdAddex, rt, ra, rb, cy); }
  inline Error addpcis(const Gp& rt, const Imm& d) { return _emitter()->_emitI(Inst::kIdAddpcis, rt, d); }
  inline Error mulld(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMulld, rt, ra, rb); }
  inline Error mullw(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMullw, rt, ra, rb); }
  inline Error mulhdu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMulhdu, rt, ra, rb); }
  inline Error mulhd(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMulhd, rt, ra, rb); }
  inline Error mulhw(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMulhw, rt, ra, rb); }
  inline Error mulhwu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMulhwu, rt, ra, rb); }
  inline Error mulli(const Gp& rt, const Gp& ra, const Imm& simm) { return _emitter()->_emitI(Inst::kIdMulli, rt, ra, simm); }
  inline Error maddhd(const Gp& rt, const Gp& ra, const Gp& rb, const Gp& rc0) { return _emitter()->_emitI(Inst::kIdMaddhd, rt, ra, rb, rc0); }
  inline Error maddhdu(const Gp& rt, const Gp& ra, const Gp& rb, const Gp& rc0) { return _emitter()->_emitI(Inst::kIdMaddhdu, rt, ra, rb, rc0); }
  inline Error maddld(const Gp& rt, const Gp& ra, const Gp& rb, const Gp& rc0) { return _emitter()->_emitI(Inst::kIdMaddld, rt, ra, rb, rc0); }
  inline Error divd(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivd, rt, ra, rb); }
  inline Error divw(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivw, rt, ra, rb); }
  inline Error divdu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivdu, rt, ra, rb); }
  inline Error divwu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivwu, rt, ra, rb); }
  inline Error divde(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivde, rt, ra, rb); }
  inline Error divdeu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivdeu, rt, ra, rb); }
  inline Error divwe(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivwe, rt, ra, rb); }
  inline Error divweu(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDivweu, rt, ra, rb); }
  inline Error modsd(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdModsd, rt, ra, rb); }
  inline Error modud(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdModud, rt, ra, rb); }
  inline Error modsw(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdModsw, rt, ra, rb); }
  inline Error moduw(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdModuw, rt, ra, rb); }
  inline Error darn(const Gp& rt, const Imm& l) { return _emitter()->_emitI(Inst::kIdDarn, rt, l); }
  inline Error srawi(const Gp& ra, const Gp& rs, const Imm& sh) { return _emitter()->_emitI(Inst::kIdSrawi, ra, rs, sh); }
  inline Error srdi(const Gp& ra, const Gp& rs, const Imm& sh) { return _emitter()->_emitI(Inst::kIdSrdi, ra, rs, sh); }
  inline Error andi_(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdAndi_, ra, rs, uimm); }
  inline Error andis_(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdAndis_, ra, rs, uimm); }
  inline Error xori(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdXori, ra, rs, uimm); }
  inline Error xoris(const Gp& ra, const Gp& rs, const Imm& uimm) { return _emitter()->_emitI(Inst::kIdXoris, ra, rs, uimm); }
  inline Error cmpd(const Gp& ra, const Gp& rb, const Imm& bf = imm(0)) { return _emitter()->_emitI(Inst::kIdCmpd, ra, rb, bf); }
  inline Error cmpld(const Gp& ra, const Gp& rb, const Imm& bf = imm(0)) { return _emitter()->_emitI(Inst::kIdCmpld, ra, rb, bf); }
  inline Error cmpdi(const Gp& ra, const Imm& simm, const Imm& bf = imm(0)) { return _emitter()->_emitI(Inst::kIdCmpdi, ra, simm, bf); }
  inline Error cmp(const Imm& bf, const Imm& l, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdCmp, bf, l, ra, rb); }
  inline Error cmpl(const Imm& bf, const Imm& l, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdCmpl, bf, l, ra, rb); }
  inline Error cmpi(const Imm& bf, const Imm& l, const Gp& ra, const Imm& si) { return _emitter()->_emitI(Inst::kIdCmpi, bf, l, ra, si); }
  inline Error cmpli(const Imm& bf, const Imm& l, const Gp& ra, const Imm& ui) { return _emitter()->_emitI(Inst::kIdCmpli, bf, l, ra, ui); }
  inline Error cmpldi(const Imm& bf, const Gp& ra, const Imm& ui) { return _emitter()->_emitI(Inst::kIdCmpldi, bf, ra, ui); }
  inline Error cmpb(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdCmpb, ra, rs, rb); }
  inline Error cmpeqb(const Imm& bf, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdCmpeqb, bf, ra, rb); }
  inline Error cmprb(const Imm& bf, const Imm& l, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdCmprb, bf, l, ra, rb); }
  inline Error tw(const Imm& to, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdTw, to, ra, rb); }
  inline Error twi(const Imm& to, const Gp& ra, const Imm& si) { return _emitter()->_emitI(Inst::kIdTwi, to, ra, si); }
  inline Error td(const Imm& to, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdTd, to, ra, rb); }
  inline Error tdi(const Imm& to, const Gp& ra, const Imm& si) { return _emitter()->_emitI(Inst::kIdTdi, to, ra, si); }
  inline Error isel(const Gp& rt, const Gp& ra, const Gp& rb, const Imm& bc) { return _emitter()->_emitI(Inst::kIdIsel, rt, ra, rb, bc); }
  inline Error isellt(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdIsellt, rt, ra, rb); }
  inline Error iseleq(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdIseleq, rt, ra, rb); }
  inline Error iselgt(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdIselgt, rt, ra, rb); }
  inline Error beq(const Label& label) { return _emitter()->_emitI(Inst::kIdBeq, label); }
  inline Error bne(const Label& label) { return _emitter()->_emitI(Inst::kIdBne, label); }
  inline Error blt(const Label& label) { return _emitter()->_emitI(Inst::kIdBlt, label); }
  inline Error bge(const Label& label) { return _emitter()->_emitI(Inst::kIdBge, label); }
  inline Error bgt(const Label& label) { return _emitter()->_emitI(Inst::kIdBgt, label); }
  inline Error ble(const Label& label) { return _emitter()->_emitI(Inst::kIdBle, label); }
  inline Error b(const Label& label) { return _emitter()->_emitI(Inst::kIdB, label); }
  inline Error bc(const Imm& bo, const Imm& bi, const Label& label) { return _emitter()->_emitI(Inst::kIdBc, bo, bi, label); }
  inline Error bcl(const Imm& bo, const Imm& bi, const Label& label) { return _emitter()->_emitI(Inst::kIdBcl, bo, bi, label); }
  inline Error bclr(const Imm& bo, const Imm& bi, const Imm& bh = imm(0)) { return _emitter()->_emitI(Inst::kIdBclr, bo, bi, bh); }
  inline Error bclrl(const Imm& bo, const Imm& bi, const Imm& bh = imm(0)) { return _emitter()->_emitI(Inst::kIdBclrl, bo, bi, bh); }
  inline Error bcctr(const Imm& bo, const Imm& bi, const Imm& bh = imm(0)) { return _emitter()->_emitI(Inst::kIdBcctr, bo, bi, bh); }
  inline Error bcctrl(const Imm& bo, const Imm& bi, const Imm& bh = imm(0)) { return _emitter()->_emitI(Inst::kIdBcctrl, bo, bi, bh); }
  inline Error mtctr(const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtctr, rs); }
  inline Error bctrl() { return _emitter()->_emitI(Inst::kIdBctrl); }
  inline Error bctr() { return _emitter()->_emitI(Inst::kIdBctr); }
  inline Error mflr(const Gp& rt) { return _emitter()->_emitI(Inst::kIdMflr, rt); }
  inline Error mtlr(const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtlr, rs); }
  inline Error blr() { return _emitter()->_emitI(Inst::kIdBlr); }
  inline Error nop() { return _emitter()->_emitI(Inst::kIdNop); }
  inline Error ld(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLd, rt, m); }
  inline Error std(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStd, rs, m); }
  inline Error stdu(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStdu, rs, m); }
  inline Error lwz(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwz, rt, m); }
  inline Error stw(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStw, rs, m); }
  inline Error lbz(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLbz, rt, m); }
  inline Error lbzu(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLbzu, rt, m); }
  inline Error stb(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStb, rs, m); }
  inline Error stbu(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStbu, rs, m); }
  inline Error lhz(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhz, rt, m); }
  inline Error lhzu(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhzu, rt, m); }
  inline Error lha(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLha, rt, m); }
  inline Error lhau(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhau, rt, m); }
  inline Error sth(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSth, rs, m); }
  inline Error sthu(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSthu, rs, m); }
  inline Error lwzu(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwzu, rt, m); }
  inline Error stwu(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStwu, rs, m); }
  inline Error lwa(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwa, rt, m); }
  inline Error ldu(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLdu, rt, m); }
  inline Error lbzx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLbzx, rt, m); }
  inline Error lbzux(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLbzux, rt, m); }
  inline Error lhzx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhzx, rt, m); }
  inline Error lhzux(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhzux, rt, m); }
  inline Error lhax(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhax, rt, m); }
  inline Error lhaux(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhaux, rt, m); }
  inline Error lwzx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwzx, rt, m); }
  inline Error lwzux(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwzux, rt, m); }
  inline Error lwax(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwax, rt, m); }
  inline Error ldx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLdx, rt, m); }
  inline Error ldux(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLdux, rt, m); }
  inline Error stbx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStbx, rs, m); }
  inline Error stbux(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStbux, rs, m); }
  inline Error sthx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSthx, rs, m); }
  inline Error sthux(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSthux, rs, m); }
  inline Error stwx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStwx, rs, m); }
  inline Error stwux(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStwux, rs, m); }
  inline Error stdx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStdx, rs, m); }
  inline Error stdux(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStdux, rs, m); }
  inline Error lhbrx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLhbrx, rt, m); }
  inline Error lwbrx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwbrx, rt, m); }
  inline Error ldbrx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLdbrx, rt, m); }
  inline Error sthbrx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSthbrx, rs, m); }
  inline Error stwbrx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStwbrx, rs, m); }
  inline Error stdbrx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStdbrx, rs, m); }
  inline Error lmw(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLmw, rt, m); }
  inline Error stmw(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStmw, rs, m); }
  inline Error lswi(const Gp& rt, const Gp& ra, const Imm& nb) { return _emitter()->_emitI(Inst::kIdLswi, rt, ra, nb); }
  inline Error lswx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLswx, rt, m); }
  inline Error stswi(const Gp& rs, const Gp& ra, const Imm& nb) { return _emitter()->_emitI(Inst::kIdStswi, rs, ra, nb); }
  inline Error stswx(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStswx, rs, m); }
  inline Error lwarx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLwarx, rt, m); }
  inline Error ldarx(const Gp& rt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLdarx, rt, m); }
  inline Error lbarx(const Gp& rt, const Mem& m, const Imm& eh = imm(0)) { return _emitter()->_emitI(Inst::kIdLbarx, rt, m, eh); }
  inline Error lharx(const Gp& rt, const Mem& m, const Imm& eh = imm(0)) { return _emitter()->_emitI(Inst::kIdLharx, rt, m, eh); }
  inline Error stwcx_(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStwcx_, rs, m); }
  inline Error stdcx_(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStdcx_, rs, m); }
  inline Error stbcx_(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStbcx_, rs, m); }
  inline Error sthcx_(const Gp& rs, const Mem& m) { return _emitter()->_emitI(Inst::kIdSthcx_, rs, m); }
  inline Error rldicl(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& mb) { return _emitter()->_emitI(Inst::kIdRldicl, ra, rs, sh, mb); }
  inline Error rldicr(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& me) { return _emitter()->_emitI(Inst::kIdRldicr, ra, rs, sh, me); }
  inline Error rldic(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& mb) { return _emitter()->_emitI(Inst::kIdRldic, ra, rs, sh, mb); }
  inline Error rlwinm(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& mb, const Imm& me) { return _emitter()->_emitI(Inst::kIdRlwinm, ra, rs, sh, mb, me); }
  inline Error rlwimi(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& mb, const Imm& me) { return _emitter()->_emitI(Inst::kIdRlwimi, ra, rs, sh, mb, me); }
  inline Error rldimi(const Gp& ra, const Gp& rs, const Imm& sh, const Imm& mb) { return _emitter()->_emitI(Inst::kIdRldimi, ra, rs, sh, mb); }
  inline Error rlwnm(const Gp& ra, const Gp& rs, const Gp& rb, const Imm& mb, const Imm& me) { return _emitter()->_emitI(Inst::kIdRlwnm, ra, rs, rb, mb, me); }
  inline Error rldcl(const Gp& ra, const Gp& rs, const Gp& rb, const Imm& mb) { return _emitter()->_emitI(Inst::kIdRldcl, ra, rs, rb, mb); }
  inline Error rldcr(const Gp& ra, const Gp& rs, const Gp& rb, const Imm& me) { return _emitter()->_emitI(Inst::kIdRldcr, ra, rs, rb, me); }
  inline Error clrldi(const Gp& ra, const Gp& rs, const Imm& n) { return _emitter()->_emitI(Inst::kIdClrldi, ra, rs, n); }
  inline Error clrrdi(const Gp& ra, const Gp& rs, const Imm& n) { return _emitter()->_emitI(Inst::kIdClrrdi, ra, rs, n); }
  inline Error rotldi(const Gp& ra, const Gp& rs, const Imm& n) { return _emitter()->_emitI(Inst::kIdRotldi, ra, rs, n); }
  inline Error rotrdi(const Gp& ra, const Gp& rs, const Imm& n) { return _emitter()->_emitI(Inst::kIdRotrdi, ra, rs, n); }
  inline Error extldi(const Gp& ra, const Gp& rs, const Imm& n, const Imm& b) { return _emitter()->_emitI(Inst::kIdExtldi, ra, rs, n, b); }
  inline Error extrdi(const Gp& ra, const Gp& rs, const Imm& n, const Imm& b) { return _emitter()->_emitI(Inst::kIdExtrdi, ra, rs, n, b); }
  inline Error insrdi(const Gp& ra, const Gp& rs, const Imm& n, const Imm& b) { return _emitter()->_emitI(Inst::kIdInsrdi, ra, rs, n, b); }
  inline Error sync() { return _emitter()->_emitI(Inst::kIdSync); }
  inline Error lwsync() { return _emitter()->_emitI(Inst::kIdLwsync); }
  inline Error isync() { return _emitter()->_emitI(Inst::kIdIsync); }
  inline Error eieio() { return _emitter()->_emitI(Inst::kIdEieio); }
  inline Error wait(const Imm& wc = imm(0)) { return _emitter()->_emitI(Inst::kIdWait, wc); }
  inline Error dcbf(const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDcbf, ra, rb); }
  inline Error dcbst(const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDcbst, ra, rb); }
  inline Error dcbt(const Gp& ra, const Gp& rb, const Imm& th = imm(0)) { return _emitter()->_emitI(Inst::kIdDcbt, ra, rb, th); }
  inline Error dcbtst(const Gp& ra, const Gp& rb, const Imm& th = imm(0)) { return _emitter()->_emitI(Inst::kIdDcbtst, ra, rb, th); }
  inline Error dcbz(const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdDcbz, ra, rb); }
  inline Error icbi(const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdIcbi, ra, rb); }
  inline Error icbt(const Imm& ct, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdIcbt, ct, ra, rb); }
  inline Error cntlzw(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCntlzw, ra, rs); }
  inline Error cntlzd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCntlzd, ra, rs); }
  inline Error cnttzw(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCnttzw, ra, rs); }
  inline Error cnttzd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCnttzd, ra, rs); }
  inline Error popcntd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdPopcntd, ra, rs); }
  inline Error popcntb(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdPopcntb, ra, rs); }
  inline Error popcntw(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdPopcntw, ra, rs); }
  inline Error prtyd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdPrtyd, ra, rs); }
  inline Error prtyw(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdPrtyw, ra, rs); }
  inline Error bpermd(const Gp& ra, const Gp& rs, const Gp& rb) { return _emitter()->_emitI(Inst::kIdBpermd, ra, rs, rb); }
  inline Error extsb(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdExtsb, ra, rs); }
  inline Error extsh(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdExtsh, ra, rs); }
  inline Error mfcr(const Gp& rt) { return _emitter()->_emitI(Inst::kIdMfcr, rt); }
  inline Error mtcrf(const Imm& fxm, const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtcrf, fxm, rs); }
  inline Error mfocrf(const Gp& rt, const Imm& fxm) { return _emitter()->_emitI(Inst::kIdMfocrf, rt, fxm); }
  inline Error mtocrf(const Imm& fxm, const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtocrf, fxm, rs); }
  inline Error mcrxrx(const Imm& bf) { return _emitter()->_emitI(Inst::kIdMcrxrx, bf); }
  inline Error mfspr(const Gp& rt, const Imm& spr) { return _emitter()->_emitI(Inst::kIdMfspr, rt, spr); }
  inline Error mtspr(const Imm& spr, const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtspr, spr, rs); }
  inline Error mfxer(const Gp& rt) { return _emitter()->_emitI(Inst::kIdMfxer, rt); }
  inline Error mtxer(const Gp& rs) { return _emitter()->_emitI(Inst::kIdMtxer, rs); }
  inline Error setb(const Gp& rt, const Imm& bfa) { return _emitter()->_emitI(Inst::kIdSetb, rt, bfa); }
  inline Error mcrf(const Imm& bf, const Imm& bfa) { return _emitter()->_emitI(Inst::kIdMcrf, bf, bfa); }
  inline Error crand(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrand, bt, ba, bb); }
  inline Error crandc(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrandc, bt, ba, bb); }
  inline Error crnor(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrnor, bt, ba, bb); }
  inline Error creqv(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCreqv, bt, ba, bb); }
  inline Error crnand(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrnand, bt, ba, bb); }
  inline Error cror(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCror, bt, ba, bb); }
  inline Error crorc(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrorc, bt, ba, bb); }
  inline Error crxor(const Imm& bt, const Imm& ba, const Imm& bb) { return _emitter()->_emitI(Inst::kIdCrxor, bt, ba, bb); }
  inline Error crclr(const Imm& bt) { return _emitter()->_emitI(Inst::kIdCrclr, bt); }
  inline Error crset(const Imm& bt) { return _emitter()->_emitI(Inst::kIdCrset, bt); }
  inline Error crmove(const Imm& bt, const Imm& ba) { return _emitter()->_emitI(Inst::kIdCrmove, bt, ba); }
  inline Error crnot(const Imm& bt, const Imm& ba) { return _emitter()->_emitI(Inst::kIdCrnot, bt, ba); }
  inline Error sc(const Imm& lev = imm(0)) { return _emitter()->_emitI(Inst::kIdSc, lev); }
  inline Error scv(const Imm& lev = imm(0)) { return _emitter()->_emitI(Inst::kIdScv, lev); }
  inline Error addg6s(const Gp& rt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdAddg6s, rt, ra, rb); }
  inline Error cbcdtd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCbcdtd, ra, rs); }
  inline Error cdtbcd(const Gp& ra, const Gp& rs) { return _emitter()->_emitI(Inst::kIdCdtbcd, ra, rs); }
  inline Error lfs(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfs, frt, m); }
  inline Error lfsu(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfsu, frt, m); }
  inline Error lfsx(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfsx, frt, m); }
  inline Error lfsux(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfsux, frt, m); }
  inline Error lfd(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfd, frt, m); }
  inline Error lfdu(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfdu, frt, m); }
  inline Error lfdx(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfdx, frt, m); }
  inline Error lfdux(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfdux, frt, m); }
  inline Error lfiwax(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfiwax, frt, m); }
  inline Error lfiwzx(const Fp& frt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLfiwzx, frt, m); }
  inline Error stfs(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfs, frs, m); }
  inline Error stfsu(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfsu, frs, m); }
  inline Error stfsx(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfsx, frs, m); }
  inline Error stfsux(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfsux, frs, m); }
  inline Error stfd(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfd, frs, m); }
  inline Error stfdu(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfdu, frs, m); }
  inline Error stfdx(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfdx, frs, m); }
  inline Error stfdux(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfdux, frs, m); }
  inline Error stfiwx(const Fp& frs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStfiwx, frs, m); }
  inline Error fmr(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFmr, frt, frb); }
  inline Error fneg(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFneg, frt, frb); }
  inline Error fabs(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFabs, frt, frb); }
  inline Error fnabs(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFnabs, frt, frb); }
  inline Error fcpsgn(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcpsgn, frt, fra, frb); }
  inline Error fadd(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFadd, frt, fra, frb); }
  inline Error fadds(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFadds, frt, fra, frb); }
  inline Error fsub(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFsub, frt, fra, frb); }
  inline Error fsubs(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFsubs, frt, fra, frb); }
  inline Error fmul(const Fp& frt, const Fp& fra, const Fp& frc) { return _emitter()->_emitI(Inst::kIdFmul, frt, fra, frc); }
  inline Error fmuls(const Fp& frt, const Fp& fra, const Fp& frc) { return _emitter()->_emitI(Inst::kIdFmuls, frt, fra, frc); }
  inline Error fdiv(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFdiv, frt, fra, frb); }
  inline Error fdivs(const Fp& frt, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFdivs, frt, fra, frb); }
  inline Error fsqrt(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFsqrt, frt, frb); }
  inline Error fsqrts(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFsqrts, frt, frb); }
  inline Error fre(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFre, frt, frb); }
  inline Error fres(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFres, frt, frb); }
  inline Error frsqrte(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrsqrte, frt, frb); }
  inline Error frsqrtes(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrsqrtes, frt, frb); }
  inline Error fmadd(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFmadd, frt, fra, frc, frb); }
  inline Error fmadds(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFmadds, frt, fra, frc, frb); }
  inline Error fmsub(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFmsub, frt, fra, frc, frb); }
  inline Error fmsubs(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFmsubs, frt, fra, frc, frb); }
  inline Error fnmadd(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFnmadd, frt, fra, frc, frb); }
  inline Error fnmadds(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFnmadds, frt, fra, frc, frb); }
  inline Error fnmsub(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFnmsub, frt, fra, frc, frb); }
  inline Error fnmsubs(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFnmsubs, frt, fra, frc, frb); }
  inline Error frin(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrin, frt, frb); }
  inline Error friz(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFriz, frt, frb); }
  inline Error frip(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrip, frt, frb); }
  inline Error frim(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrim, frt, frb); }
  inline Error frsp(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFrsp, frt, frb); }
  inline Error fcfid(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcfid, frt, frb); }
  inline Error fcfidu(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcfidu, frt, frb); }
  inline Error fcfids(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcfids, frt, frb); }
  inline Error fcfidus(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcfidus, frt, frb); }
  inline Error fctiw(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctiw, frt, frb); }
  inline Error fctiwz(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctiwz, frt, frb); }
  inline Error fctiwu(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctiwu, frt, frb); }
  inline Error fctiwuz(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctiwuz, frt, frb); }
  inline Error fctid(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctid, frt, frb); }
  inline Error fctidz(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctidz, frt, frb); }
  inline Error fctidu(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctidu, frt, frb); }
  inline Error fctiduz(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFctiduz, frt, frb); }
  inline Error fcmpu(const Imm& bf, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcmpu, bf, fra, frb); }
  inline Error fcmpo(const Imm& bf, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFcmpo, bf, fra, frb); }
  inline Error ftdiv(const Imm& bf, const Fp& fra, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFtdiv, bf, fra, frb); }
  inline Error ftsqrt(const Imm& bf, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFtsqrt, bf, frb); }
  inline Error fsel(const Fp& frt, const Fp& fra, const Fp& frc, const Fp& frb) { return _emitter()->_emitI(Inst::kIdFsel, frt, fra, frc, frb); }
  inline Error mffs(const Fp& frt) { return _emitter()->_emitI(Inst::kIdMffs, frt); }
  inline Error mffsce(const Fp& frt) { return _emitter()->_emitI(Inst::kIdMffsce, frt); }
  inline Error mffsl(const Fp& frt) { return _emitter()->_emitI(Inst::kIdMffsl, frt); }
  inline Error mffscrn(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdMffscrn, frt, frb); }
  inline Error mffscrni(const Fp& frt, const Imm& rm) { return _emitter()->_emitI(Inst::kIdMffscrni, frt, rm); }
  inline Error mffscdrn(const Fp& frt, const Fp& frb) { return _emitter()->_emitI(Inst::kIdMffscdrn, frt, frb); }
  inline Error mffscdrni(const Fp& frt, const Imm& drm) { return _emitter()->_emitI(Inst::kIdMffscdrni, frt, drm); }
  inline Error mtfsf(const Imm& fxm, const Fp& frb) { return _emitter()->_emitI(Inst::kIdMtfsf, fxm, frb); }
  inline Error mtfsb0(const Imm& crb) { return _emitter()->_emitI(Inst::kIdMtfsb0, crb); }
  inline Error mtfsb1(const Imm& crb) { return _emitter()->_emitI(Inst::kIdMtfsb1, crb); }
  inline Error mtfsfi(const Imm& bf, const Imm& imm) { return _emitter()->_emitI(Inst::kIdMtfsfi, bf, imm); }
  inline Error mcrfs(const Imm& bf, const Imm& bfa) { return _emitter()->_emitI(Inst::kIdMcrfs, bf, bfa); }
  inline Error mfvsrd(const Gp& rt, const Vsx& xs) { return _emitter()->_emitI(Inst::kIdMfvsrd, rt, xs); }
  inline Error mfvsrld(const Gp& rt, const Vsx& xs) { return _emitter()->_emitI(Inst::kIdMfvsrld, rt, xs); }
  inline Error mfvsrwz(const Gp& rt, const Vsx& xs) { return _emitter()->_emitI(Inst::kIdMfvsrwz, rt, xs); }
  inline Error mtvsrd(const Vsx& xt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdMtvsrd, xt, ra); }
  inline Error mtvsrdd(const Vsx& xt, const Gp& ra, const Gp& rb) { return _emitter()->_emitI(Inst::kIdMtvsrdd, xt, ra, rb); }
  inline Error mtvsrwa(const Vsx& xt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdMtvsrwa, xt, ra); }
  inline Error mtvsrws(const Vsx& xt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdMtvsrws, xt, ra); }
  inline Error mtvsrwz(const Vsx& xt, const Gp& ra) { return _emitter()->_emitI(Inst::kIdMtvsrwz, xt, ra); }
  inline Error mfvrd(const Gp& rt, const Vr& vr) { return _emitter()->_emitI(Inst::kIdMfvrd, rt, vr); }
  inline Error mfvrwz(const Gp& rt, const Vr& vr) { return _emitter()->_emitI(Inst::kIdMfvrwz, rt, vr); }
  inline Error mtvrd(const Vr& vr, const Gp& rt) { return _emitter()->_emitI(Inst::kIdMtvrd, vr, rt); }
  inline Error mtvrwa(const Vr& vr, const Gp& rt) { return _emitter()->_emitI(Inst::kIdMtvrwa, vr, rt); }
  inline Error mtvrwz(const Vr& vr, const Gp& rt) { return _emitter()->_emitI(Inst::kIdMtvrwz, vr, rt); }
  inline Error lxsd(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxsd, xt, m); }
  inline Error lxssp(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxssp, xt, m); }
  inline Error lxsdx(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxsdx, xt, m); }
  inline Error lxsspx(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxsspx, xt, m); }
  inline Error lxsiwzx(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxsiwzx, xt, m); }
  inline Error lxsiwax(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxsiwax, xt, m); }
  inline Error lxv(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxv, xt, m); }
  inline Error lxvx(const Vsx& xt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLxvx, xt, m); }
  inline Error stxsd(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxsd, xs, m); }
  inline Error stxssp(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxssp, xs, m); }
  inline Error stxsdx(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxsdx, xs, m); }
  inline Error stxsspx(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxsspx, xs, m); }
  inline Error stxsiwx(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxsiwx, xs, m); }
  inline Error stxv(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxv, xs, m); }
  inline Error stxvx(const Vsx& xs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStxvx, xs, m); }
  inline Error xsabsdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsabsdp, xt, xb); }
  inline Error xsadddp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsadddp, xt, xa, xb); }
  inline Error xscpsgndp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscpsgndp, xt, xa, xb); }
  inline Error xsdivdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsdivdp, xt, xa, xb); }
  inline Error xsmaddadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmaddadp, xt, xa, xb); }
  inline Error xsmaddmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmaddmdp, xt, xa, xb); }
  inline Error xsmsubadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmsubadp, xt, xa, xb); }
  inline Error xsmsubmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmsubmdp, xt, xa, xb); }
  inline Error xsmuldp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmuldp, xt, xa, xb); }
  inline Error xsnegdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnegdp, xt, xb); }
  inline Error xsnmsubadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmsubadp, xt, xa, xb); }
  inline Error xsnmsubmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmsubmdp, xt, xa, xb); }
  inline Error xsnmaddadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmaddadp, xt, xa, xb); }
  inline Error xsnmaddmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmaddmdp, xt, xa, xb); }
  inline Error xssqrtdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXssqrtdp, xt, xb); }
  inline Error xssubdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXssubdp, xt, xa, xb); }
  inline Error xsaddsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsaddsp, xt, xa, xb); }
  inline Error xsdivsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsdivsp, xt, xa, xb); }
  inline Error xsmaddasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmaddasp, xt, xa, xb); }
  inline Error xsmaddmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmaddmsp, xt, xa, xb); }
  inline Error xsmsubasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmsubasp, xt, xa, xb); }
  inline Error xsmsubmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmsubmsp, xt, xa, xb); }
  inline Error xsmulsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsmulsp, xt, xa, xb); }
  inline Error xsnmsubasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmsubasp, xt, xa, xb); }
  inline Error xsnmsubmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmsubmsp, xt, xa, xb); }
  inline Error xsnmaddasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmaddasp, xt, xa, xb); }
  inline Error xsnmaddmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsnmaddmsp, xt, xa, xb); }
  inline Error xssqrtsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXssqrtsp, xt, xb); }
  inline Error xssubsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXssubsp, xt, xa, xb); }
  inline Error xscmpudp(const Imm& bf, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscmpudp, bf, xa, xb); }
  inline Error xscmpodp(const Imm& bf, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscmpodp, bf, xa, xb); }
  inline Error xscmpeqdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscmpeqdp, xt, xa, xb); }
  inline Error xscmpgedp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscmpgedp, xt, xa, xb); }
  inline Error xscmpgtdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscmpgtdp, xt, xa, xb); }
  inline Error xstdivdp(const Imm& bf, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXstdivdp, bf, xa, xb); }
  inline Error xstsqrtdp(const Imm& bf, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXstsqrtdp, bf, xb); }
  inline Error xsrdpi(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsrdpi, xt, xb); }
  inline Error xsrdpic(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsrdpic, xt, xb); }
  inline Error xsrdpiz(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsrdpiz, xt, xb); }
  inline Error xsrdpip(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsrdpip, xt, xb); }
  inline Error xsrdpim(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXsrdpim, xt, xb); }
  inline Error xscvdpsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvdpsp, xt, xb); }
  inline Error xscvspdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvspdp, xt, xb); }
  inline Error xscvdpsxds(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvdpsxds, xt, xb); }
  inline Error xscvdpuxds(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvdpuxds, xt, xb); }
  inline Error xscvsxddp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvsxddp, xt, xb); }
  inline Error xscvuxddp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvuxddp, xt, xb); }
  inline Error xscvdpsxws(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvdpsxws, xt, xb); }
  inline Error xscvdpuxws(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvdpuxws, xt, xb); }
  inline Error xscvsxdsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvsxdsp, xt, xb); }
  inline Error xscvuxdsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXscvuxdsp, xt, xb); }
  inline Error xvadddp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvadddp, xt, xa, xb); }
  inline Error xvaddsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvaddsp, xt, xa, xb); }
  inline Error xvsubdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvsubdp, xt, xa, xb); }
  inline Error xvsubsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvsubsp, xt, xa, xb); }
  inline Error xvmuldp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmuldp, xt, xa, xb); }
  inline Error xvmulsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmulsp, xt, xa, xb); }
  inline Error xvdivdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvdivdp, xt, xa, xb); }
  inline Error xvdivsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvdivsp, xt, xa, xb); }
  inline Error xvmaddadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaddadp, xt, xa, xb); }
  inline Error xvmaddmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaddmdp, xt, xa, xb); }
  inline Error xvmsubadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmsubadp, xt, xa, xb); }
  inline Error xvmsubmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmsubmdp, xt, xa, xb); }
  inline Error xvnmaddadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmaddadp, xt, xa, xb); }
  inline Error xvnmaddmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmaddmdp, xt, xa, xb); }
  inline Error xvnmsubadp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmsubadp, xt, xa, xb); }
  inline Error xvnmsubmdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmsubmdp, xt, xa, xb); }
  inline Error xvmaddasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaddasp, xt, xa, xb); }
  inline Error xvmaddmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaddmsp, xt, xa, xb); }
  inline Error xvmsubasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmsubasp, xt, xa, xb); }
  inline Error xvmsubmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmsubmsp, xt, xa, xb); }
  inline Error xvnmaddasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmaddasp, xt, xa, xb); }
  inline Error xvnmaddmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmaddmsp, xt, xa, xb); }
  inline Error xvnmsubasp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmsubasp, xt, xa, xb); }
  inline Error xvnmsubmsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnmsubmsp, xt, xa, xb); }
  inline Error xvmaxdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaxdp, xt, xa, xb); }
  inline Error xvmindp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmindp, xt, xa, xb); }
  inline Error xvmaxsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvmaxsp, xt, xa, xb); }
  inline Error xvminsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvminsp, xt, xa, xb); }
  inline Error xvcmpeqdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpeqdp, xt, xa, xb); }
  inline Error xvcmpgtdp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpgtdp, xt, xa, xb); }
  inline Error xvcmpgedp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpgedp, xt, xa, xb); }
  inline Error xvcmpeqsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpeqsp, xt, xa, xb); }
  inline Error xvcmpgtsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpgtsp, xt, xa, xb); }
  inline Error xvcmpgesp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcmpgesp, xt, xa, xb); }
  inline Error xvabsdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvabsdp, xt, xb); }
  inline Error xvabssp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvabssp, xt, xb); }
  inline Error xvnabsdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnabsdp, xt, xb); }
  inline Error xvnabssp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnabssp, xt, xb); }
  inline Error xvnegdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnegdp, xt, xb); }
  inline Error xvnegsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvnegsp, xt, xb); }
  inline Error xvcpsgndp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcpsgndp, xt, xa, xb); }
  inline Error xvcpsgnsp(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcpsgnsp, xt, xa, xb); }
  inline Error xvsqrtdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvsqrtdp, xt, xb); }
  inline Error xvsqrtsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvsqrtsp, xt, xb); }
  inline Error xvrsqrtedp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvrsqrtedp, xt, xb); }
  inline Error xvrsqrtesp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvrsqrtesp, xt, xb); }
  inline Error xvcvsxwdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvsxwdp, xt, xb); }
  inline Error xvcvuxwdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvuxwdp, xt, xb); }
  inline Error xvcvsxwsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvsxwsp, xt, xb); }
  inline Error xvcvuxwsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvuxwsp, xt, xb); }
  inline Error xvcvdpsxws(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvdpsxws, xt, xb); }
  inline Error xvcvdpuxws(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvdpuxws, xt, xb); }
  inline Error xvcvdpsxds(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvdpsxds, xt, xb); }
  inline Error xvcvdpuxds(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvdpuxds, xt, xb); }
  inline Error xvcvsxddp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvsxddp, xt, xb); }
  inline Error xvcvuxddp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvuxddp, xt, xb); }
  inline Error xvcvdpsp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvdpsp, xt, xb); }
  inline Error xvcvspdp(const Vsx& xt, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXvcvspdp, xt, xb); }
  inline Error xxlxor(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlxor, xt, xa, xb); }
  inline Error xxlor(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlor, xt, xa, xb); }
  inline Error xxland(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxland, xt, xa, xb); }
  inline Error xxlandc(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlandc, xt, xa, xb); }
  inline Error xxlorc(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlorc, xt, xa, xb); }
  inline Error xxlnand(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlnand, xt, xa, xb); }
  inline Error xxlnor(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxlnor, xt, xa, xb); }
  inline Error xxleqv(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxleqv, xt, xa, xb); }
  inline Error xxsel(const Vsx& xt, const Vsx& xa, const Vsx& xb, const Vsx& xc) { return _emitter()->_emitI(Inst::kIdXxsel, xt, xa, xb, xc); }
  inline Error xxperm(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxperm, xt, xa, xb); }
  inline Error xxpermdi(const Vsx& xt, const Vsx& xa, const Vsx& xb, const Imm& dm) { return _emitter()->_emitI(Inst::kIdXxpermdi, xt, xa, xb, dm); }
  inline Error xxmrghd(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxmrghd, xt, xa, xb); }
  inline Error xxmrgld(const Vsx& xt, const Vsx& xa, const Vsx& xb) { return _emitter()->_emitI(Inst::kIdXxmrgld, xt, xa, xb); }
  inline Error xxspltd(const Vsx& xt, const Vsx& xb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdXxspltd, xt, xb, uim); }
  inline Error xxspltw(const Vsx& xt, const Vsx& xb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdXxspltw, xt, xb, uim); }
  inline Error xxswapd(const Vsx& xt, const Vsx& xa) { return _emitter()->_emitI(Inst::kIdXxswapd, xt, xa); }
  inline Error lvx(const Vr& vrt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLvx, vrt, m); }
  inline Error lvebx(const Vr& vrt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLvebx, vrt, m); }
  inline Error lvehx(const Vr& vrt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLvehx, vrt, m); }
  inline Error lvewx(const Vr& vrt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLvewx, vrt, m); }
  inline Error lvxl(const Vr& vrt, const Mem& m) { return _emitter()->_emitI(Inst::kIdLvxl, vrt, m); }
  inline Error stvx(const Vr& vrs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStvx, vrs, m); }
  inline Error stvebx(const Vr& vrs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStvebx, vrs, m); }
  inline Error stvehx(const Vr& vrs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStvehx, vrs, m); }
  inline Error stvewx(const Vr& vrs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStvewx, vrs, m); }
  inline Error stvxl(const Vr& vrs, const Mem& m) { return _emitter()->_emitI(Inst::kIdStvxl, vrs, m); }
  inline Error vaddubm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddubm, vrt, vra, vrb); }
  inline Error vadduhm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVadduhm, vrt, vra, vrb); }
  inline Error vadduwm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVadduwm, vrt, vra, vrb); }
  inline Error vaddudm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddudm, vrt, vra, vrb); }
  inline Error vaddcuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddcuw, vrt, vra, vrb); }
  inline Error vsububm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsububm, vrt, vra, vrb); }
  inline Error vsubuhm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubuhm, vrt, vra, vrb); }
  inline Error vsubuwm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubuwm, vrt, vra, vrb); }
  inline Error vsubudm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubudm, vrt, vra, vrb); }
  inline Error vsubcuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubcuw, vrt, vra, vrb); }
  inline Error vaddsbs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddsbs, vrt, vra, vrb); }
  inline Error vaddshs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddshs, vrt, vra, vrb); }
  inline Error vaddsws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddsws, vrt, vra, vrb); }
  inline Error vaddubs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddubs, vrt, vra, vrb); }
  inline Error vadduhs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVadduhs, vrt, vra, vrb); }
  inline Error vadduws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVadduws, vrt, vra, vrb); }
  inline Error vsubsbs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubsbs, vrt, vra, vrb); }
  inline Error vsubshs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubshs, vrt, vra, vrb); }
  inline Error vsubsws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubsws, vrt, vra, vrb); }
  inline Error vsububs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsububs, vrt, vra, vrb); }
  inline Error vsubuhs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubuhs, vrt, vra, vrb); }
  inline Error vsubuws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubuws, vrt, vra, vrb); }
  inline Error vaddcuq(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVaddcuq, vrt, vra, vrb); }
  inline Error vadduqm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVadduqm, vrt, vra, vrb); }
  inline Error vaddeuqm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVaddeuqm, vrt, vra, vrb, vrc); }
  inline Error vaddecuq(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVaddecuq, vrt, vra, vrb, vrc); }
  inline Error vsubcuq(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubcuq, vrt, vra, vrb); }
  inline Error vsubuqm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsubuqm, vrt, vra, vrb); }
  inline Error vsubeuqm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVsubeuqm, vrt, vra, vrb, vrc); }
  inline Error vsubecuq(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVsubecuq, vrt, vra, vrb, vrc); }
  inline Error vabsdub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVabsdub, vrt, vra, vrb); }
  inline Error vabsduh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVabsduh, vrt, vra, vrb); }
  inline Error vabsduw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVabsduw, vrt, vra, vrb); }
  inline Error vand(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVand, vrt, vra, vrb); }
  inline Error vandc(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVandc, vrt, vra, vrb); }
  inline Error vor(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVor, vrt, vra, vrb); }
  inline Error vxor(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVxor, vrt, vra, vrb); }
  inline Error vnor(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVnor, vrt, vra, vrb); }
  inline Error veqv(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVeqv, vrt, vra, vrb); }
  inline Error vnand(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVnand, vrt, vra, vrb); }
  inline Error vsl(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsl, vrt, vra, vrb); }
  inline Error vsr(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsr, vrt, vra, vrb); }
  inline Error vsld(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsld, vrt, vra, vrb); }
  inline Error vsrd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrd, vrt, vra, vrb); }
  inline Error vsrad(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrad, vrt, vra, vrb); }
  inline Error vslw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVslw, vrt, vra, vrb); }
  inline Error vsrw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrw, vrt, vra, vrb); }
  inline Error vsraw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsraw, vrt, vra, vrb); }
  inline Error vslb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVslb, vrt, vra, vrb); }
  inline Error vslh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVslh, vrt, vra, vrb); }
  inline Error vsrb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrb, vrt, vra, vrb); }
  inline Error vsrh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrh, vrt, vra, vrb); }
  inline Error vslo(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVslo, vrt, vra, vrb); }
  inline Error vsro(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsro, vrt, vra, vrb); }
  inline Error vslv(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVslv, vrt, vra, vrb); }
  inline Error vsrv(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsrv, vrt, vra, vrb); }
  inline Error vrlb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrlb, vrt, vra, vrb); }
  inline Error vrlh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrlh, vrt, vra, vrb); }
  inline Error vrlw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrlw, vrt, vra, vrb); }
  inline Error vrld(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrld, vrt, vra, vrb); }
  inline Error vrlwmi(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrlwmi, vrt, vra, vrb); }
  inline Error vrlwnm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrlwnm, vrt, vra, vrb); }
  inline Error vrldmi(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrldmi, vrt, vra, vrb); }
  inline Error vrldnm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVrldnm, vrt, vra, vrb); }
  inline Error vcmpequb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpequb, vrt, vra, vrb); }
  inline Error vcmpequh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpequh, vrt, vra, vrb); }
  inline Error vcmpequw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpequw, vrt, vra, vrb); }
  inline Error vcmpequd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpequd, vrt, vra, vrb); }
  inline Error vcmpgtsb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtsb, vrt, vra, vrb); }
  inline Error vcmpgtsh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtsh, vrt, vra, vrb); }
  inline Error vcmpgtsw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtsw, vrt, vra, vrb); }
  inline Error vcmpgtsd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtsd, vrt, vra, vrb); }
  inline Error vcmpgtub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtub, vrt, vra, vrb); }
  inline Error vcmpgtuh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtuh, vrt, vra, vrb); }
  inline Error vcmpgtuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtuw, vrt, vra, vrb); }
  inline Error vcmpgtud(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpgtud, vrt, vra, vrb); }
  inline Error vcmpneb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpneb, vrt, vra, vrb); }
  inline Error vcmpneh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpneh, vrt, vra, vrb); }
  inline Error vcmpnew(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpnew, vrt, vra, vrb); }
  inline Error vcmpnezb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpnezb, vrt, vra, vrb); }
  inline Error vcmpnezh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpnezh, vrt, vra, vrb); }
  inline Error vcmpnezw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVcmpnezw, vrt, vra, vrb); }
  inline Error vminub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminub, vrt, vra, vrb); }
  inline Error vminuh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminuh, vrt, vra, vrb); }
  inline Error vminuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminuw, vrt, vra, vrb); }
  inline Error vminsb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminsb, vrt, vra, vrb); }
  inline Error vminsh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminsh, vrt, vra, vrb); }
  inline Error vminsw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminsw, vrt, vra, vrb); }
  inline Error vmaxub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxub, vrt, vra, vrb); }
  inline Error vmaxuh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxuh, vrt, vra, vrb); }
  inline Error vmaxuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxuw, vrt, vra, vrb); }
  inline Error vmaxsb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxsb, vrt, vra, vrb); }
  inline Error vmaxsh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxsh, vrt, vra, vrb); }
  inline Error vmaxsw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxsw, vrt, vra, vrb); }
  inline Error vmaxsd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxsd, vrt, vra, vrb); }
  inline Error vmaxud(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmaxud, vrt, vra, vrb); }
  inline Error vminsd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminsd, vrt, vra, vrb); }
  inline Error vminud(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVminud, vrt, vra, vrb); }
  inline Error vavgub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavgub, vrt, vra, vrb); }
  inline Error vavguh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavguh, vrt, vra, vrb); }
  inline Error vavguw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavguw, vrt, vra, vrb); }
  inline Error vavgsb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavgsb, vrt, vra, vrb); }
  inline Error vavgsh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavgsh, vrt, vra, vrb); }
  inline Error vavgsw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVavgsw, vrt, vra, vrb); }
  inline Error vsum4sbs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsum4sbs, vrt, vra, vrb); }
  inline Error vsum4shs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsum4shs, vrt, vra, vrb); }
  inline Error vsum4ubs(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsum4ubs, vrt, vra, vrb); }
  inline Error vsum2sws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsum2sws, vrt, vra, vrb); }
  inline Error vsumsws(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVsumsws, vrt, vra, vrb); }
  inline Error vpkuhum(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkuhum, vrt, vra, vrb); }
  inline Error vpkuwum(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkuwum, vrt, vra, vrb); }
  inline Error vpkuhus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkuhus, vrt, vra, vrb); }
  inline Error vpkuwus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkuwus, vrt, vra, vrb); }
  inline Error vpkshss(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkshss, vrt, vra, vrb); }
  inline Error vpkswss(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkswss, vrt, vra, vrb); }
  inline Error vpkshus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkshus, vrt, vra, vrb); }
  inline Error vpkswus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkswus, vrt, vra, vrb); }
  inline Error vupkhsb(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupkhsb, vrt, vrb); }
  inline Error vupkhsh(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupkhsh, vrt, vrb); }
  inline Error vupklsb(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupklsb, vrt, vrb); }
  inline Error vupklsh(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupklsh, vrt, vrb); }
  inline Error vpkudum(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkudum, vrt, vra, vrb); }
  inline Error vpkudus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkudus, vrt, vra, vrb); }
  inline Error vpksdss(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpksdss, vrt, vra, vrb); }
  inline Error vpksdus(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpksdus, vrt, vra, vrb); }
  inline Error vupkhsw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupkhsw, vrt, vrb); }
  inline Error vupklsw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupklsw, vrt, vrb); }
  inline Error vpkpx(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpkpx, vrt, vra, vrb); }
  inline Error vupkhpx(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupkhpx, vrt, vrb); }
  inline Error vupklpx(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVupklpx, vrt, vrb); }
  inline Error vmrghb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrghb, vrt, vra, vrb); }
  inline Error vmrghh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrghh, vrt, vra, vrb); }
  inline Error vmrghw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrghw, vrt, vra, vrb); }
  inline Error vmrglb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrglb, vrt, vra, vrb); }
  inline Error vmrglh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrglh, vrt, vra, vrb); }
  inline Error vmrglw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrglw, vrt, vra, vrb); }
  inline Error vmrgew(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrgew, vrt, vra, vrb); }
  inline Error vmrgow(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmrgow, vrt, vra, vrb); }
  inline Error vspltb(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVspltb, vrt, vrb, uim); }
  inline Error vsplth(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVsplth, vrt, vrb, uim); }
  inline Error vspltw(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVspltw, vrt, vrb, uim); }
  inline Error vspltisb(const Vr& vrt, const Imm& simm) { return _emitter()->_emitI(Inst::kIdVspltisb, vrt, simm); }
  inline Error vspltish(const Vr& vrt, const Imm& simm) { return _emitter()->_emitI(Inst::kIdVspltish, vrt, simm); }
  inline Error vspltisw(const Vr& vrt, const Imm& simm) { return _emitter()->_emitI(Inst::kIdVspltisw, vrt, simm); }
  inline Error vperm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVperm, vrt, vra, vrb, vrc); }
  inline Error vsel(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVsel, vrt, vra, vrb, vrc); }
  inline Error vsldoi(const Vr& vrt, const Vr& vra, const Vr& vrb, const Imm& shb) { return _emitter()->_emitI(Inst::kIdVsldoi, vrt, vra, vrb, shb); }
  inline Error vpermr(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVpermr, vrt, vra, vrb, vrc); }
  inline Error vpermxor(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVpermxor, vrt, vra, vrb, vrc); }
  inline Error vclzb(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVclzb, vrt, vrb); }
  inline Error vclzh(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVclzh, vrt, vrb); }
  inline Error vclzw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVclzw, vrt, vrb); }
  inline Error vclzd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVclzd, vrt, vrb); }
  inline Error vpopcntb(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpopcntb, vrt, vrb); }
  inline Error vpopcnth(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpopcnth, vrt, vrb); }
  inline Error vpopcntw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpopcntw, vrt, vrb); }
  inline Error vpopcntd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpopcntd, vrt, vrb); }
  inline Error vctzb(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVctzb, vrt, vrb); }
  inline Error vctzh(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVctzh, vrt, vrb); }
  inline Error vctzw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVctzw, vrt, vrb); }
  inline Error vctzd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVctzd, vrt, vrb); }
  inline Error vclzlsbb(const Gp& rt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVclzlsbb, rt, vrb); }
  inline Error vctzlsbb(const Gp& rt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVctzlsbb, rt, vrb); }
  inline Error vmulouw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulouw, vrt, vra, vrb); }
  inline Error vmuluwm(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmuluwm, vrt, vra, vrb); }
  inline Error vmuleub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmuleub, vrt, vra, vrb); }
  inline Error vmuleuh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmuleuh, vrt, vra, vrb); }
  inline Error vmuleuw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmuleuw, vrt, vra, vrb); }
  inline Error vmulesb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulesb, vrt, vra, vrb); }
  inline Error vmulesh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulesh, vrt, vra, vrb); }
  inline Error vmulesw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulesw, vrt, vra, vrb); }
  inline Error vmuloub(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmuloub, vrt, vra, vrb); }
  inline Error vmulouh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulouh, vrt, vra, vrb); }
  inline Error vmulosb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulosb, vrt, vra, vrb); }
  inline Error vmulosh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulosh, vrt, vra, vrb); }
  inline Error vmulosw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmulosw, vrt, vra, vrb); }
  inline Error vmul10cuq(const Vr& vrt, const Vr& vra) { return _emitter()->_emitI(Inst::kIdVmul10cuq, vrt, vra); }
  inline Error vmul10uq(const Vr& vrt, const Vr& vra) { return _emitter()->_emitI(Inst::kIdVmul10uq, vrt, vra); }
  inline Error vmul10euq(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmul10euq, vrt, vra, vrb); }
  inline Error vmul10ecuq(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVmul10ecuq, vrt, vra, vrb); }
  inline Error vmhaddshs(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmhaddshs, vrt, vra, vrb, vrc); }
  inline Error vmhraddshs(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmhraddshs, vrt, vra, vrb, vrc); }
  inline Error vmladduhm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmladduhm, vrt, vra, vrb, vrc); }
  inline Error vmsummbm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsummbm, vrt, vra, vrb, vrc); }
  inline Error vmsumshm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumshm, vrt, vra, vrb, vrc); }
  inline Error vmsumshs(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumshs, vrt, vra, vrb, vrc); }
  inline Error vmsumubm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumubm, vrt, vra, vrb, vrc); }
  inline Error vmsumudm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumudm, vrt, vra, vrb, vrc); }
  inline Error vmsumuhm(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumuhm, vrt, vra, vrb, vrc); }
  inline Error vmsumuhs(const Vr& vrt, const Vr& vra, const Vr& vrb, const Vr& vrc) { return _emitter()->_emitI(Inst::kIdVmsumuhs, vrt, vra, vrb, vrc); }
  inline Error vpmsumb(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpmsumb, vrt, vra, vrb); }
  inline Error vpmsumh(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpmsumh, vrt, vra, vrb); }
  inline Error vpmsumw(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpmsumw, vrt, vra, vrb); }
  inline Error vpmsumd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVpmsumd, vrt, vra, vrb); }
  inline Error vextractub(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVextractub, vrt, vrb, uim); }
  inline Error vextractuh(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVextractuh, vrt, vrb, uim); }
  inline Error vextractuw(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVextractuw, vrt, vrb, uim); }
  inline Error vextractd(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVextractd, vrt, vrb, uim); }
  inline Error vextublx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextublx, rt, ra, vrb); }
  inline Error vextubrx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextubrx, rt, ra, vrb); }
  inline Error vextuhlx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextuhlx, rt, ra, vrb); }
  inline Error vextuhrx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextuhrx, rt, ra, vrb); }
  inline Error vextuwlx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextuwlx, rt, ra, vrb); }
  inline Error vextuwrx(const Gp& rt, const Gp& ra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextuwrx, rt, ra, vrb); }
  inline Error vinsertb(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVinsertb, vrt, vrb, uim); }
  inline Error vinserth(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVinserth, vrt, vrb, uim); }
  inline Error vinsertw(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVinsertw, vrt, vrb, uim); }
  inline Error vinsertd(const Vr& vrt, const Vr& vrb, const Imm& uim) { return _emitter()->_emitI(Inst::kIdVinsertd, vrt, vrb, uim); }
  inline Error vextsb2w(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextsb2w, vrt, vrb); }
  inline Error vextsh2w(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextsh2w, vrt, vrb); }
  inline Error vextsw2d(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextsw2d, vrt, vrb); }
  inline Error vextsb2d(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextsb2d, vrt, vrb); }
  inline Error vextsh2d(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVextsh2d, vrt, vrb); }
  inline Error vnegw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVnegw, vrt, vrb); }
  inline Error vnegd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVnegd, vrt, vrb); }
  inline Error vprtybd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVprtybd, vrt, vrb); }
  inline Error vprtybw(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVprtybw, vrt, vrb); }
  inline Error vprtybq(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVprtybq, vrt, vrb); }
  inline Error vgbbd(const Vr& vrt, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVgbbd, vrt, vrb); }
  inline Error vbpermd(const Vr& vrt, const Vr& vra, const Vr& vrb) { return _emitter()->_emitI(Inst::kIdVbpermd, vrt, vra, vrb); }

  //! \}
};

ASMJIT_END_SUB_NAMESPACE

#endif // ASMJIT_PPC_PPCEMITTER_H_INCLUDED
