#!/usr/bin/env python3
"""Generates asmjit/ppc/ppcinst.h and asmjit/ppc/ppcinstdb_p.h from the
PPC64 assembler method list.

Every `ASMJIT_API Error <name>(...)` declared in ppcassembler.h becomes an
instruction id `kId<Name>` (except the non-instruction helpers listed below).
The instruction database records the operand signature of each instruction
for assembler validation.
Run from the repository root:

  python3 tools/ppc_instgen.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "asmjit/ppc/ppcassembler.h")
OUTPUT = os.path.join(ROOT, "asmjit/ppc/ppcinst.h")
OUTPUT_DB = os.path.join(ROOT, "asmjit/ppc/ppcinstdb_p.h")
OUTPUT_EMITINST = os.path.join(ROOT, "asmjit/ppc/ppc_emitinst.inc")

# Non-instruction helpers and BaseAssembler overrides that must not become
# instruction ids.
EXCLUDED = {
    "bind", "on_attach", "on_detach", "emit32", "align", "embed", "_emit",
    "embed_label", "embed_label_delta",
    "prolog", "epilog", "call", "callDescriptor", "callHelper", "tailCall",
    "tailCallDescriptor", "bLong", "bailIfFPSpecial", "loadImm64",
}

# Parameter type -> operand kind.
KIND_BY_TYPE = {
    "Gp": "kGp",
    "Fp": "kFp",
    "Vr": "kVec",
    "Vsx": "kVec",
    "const Mem&": "kMem",
    "const Label&": "kLabel",
    "int16_t": "kImm",
    "uint16_t": "kImm",
    "uint8_t": "kImm",
    "int32_t": "kImm",
    "uint32_t": "kImm",
    "int64_t": "kImm",
    "uint64_t": "kImm",
    "bool": "kSkip",  # Trailing Rc/Oe flags, not exposed through generic emit().
}


def parse_params(args):
    """Returns (required, total, kinds) for an argument list."""
    required = 0
    total = 0
    kinds = []
    if not args.strip():
        return 0, 0, kinds
    for param in args.split(","):
        param = param.strip()
        has_default = "=" in param
        type_name = param.split("=")[0].strip().rsplit(" ", 1)[0]
        kind = KIND_BY_TYPE.get(type_name)
        if kind is None:
            raise SystemExit(f"unknown parameter type '{type_name}' in '{param}'")
        if kind == "kSkip":
            continue
        kinds.append(kind)
        total += 1
        if not has_default:
            required += 1
    return required, total, kinds


# Curated per-instruction feature requirements (PowerISA opcode-map v-tags).
FEATURE_BY_NAME = {
    # ISA 3.0 (POWER9) additions.
    "modsd": "kISA_3_0", "modsw": "kISA_3_0", "modud": "kISA_3_0", "moduw": "kISA_3_0",
    "cnttzd": "kISA_3_0", "cnttzw": "kISA_3_0", "darn": "kISA_3_0", "scv": "kISA_3_0",
    "extswsli": "kISA_3_0", "wait": "kISA_3_0", "maddhd": "kISA_3_0", "maddhdu": "kISA_3_0",
    "maddld": "kISA_3_0", "cmprb": "kISA_3_0", "setb": "kISA_3_0",
    "vclzlsbb": "kISA_3_0", "vctzlsbb": "kISA_3_0",
    "vextublx": "kISA_3_0", "vextubrx": "kISA_3_0", "vextuhlx": "kISA_3_0", "vextuhrx": "kISA_3_0",
    "vextuwlx": "kISA_3_0", "vextuwrx": "kISA_3_0",
    "vabsdub": "kISA_3_0", "vabsduh": "kISA_3_0", "vabsduw": "kISA_3_0",
    "vnegd": "kISA_3_0", "vnegw": "kISA_3_0",
    "vmul10cuq": "kISA_3_0", "vmul10ecuq": "kISA_3_0", "vmul10euq": "kISA_3_0", "vmul10uq": "kISA_3_0",
    "vbpermd": "kISA_3_0",
    # VSX loads and stores (DS/DQ/X forms).
    "lxsd": "kISA_3_0", "lxssp": "kISA_3_0", "lxv": "kISA_3_0", "lxvx": "kISA_3_0",
    "stxsd": "kISA_3_0", "stxssp": "kISA_3_0", "stxv": "kISA_3_0", "stxvx": "kISA_3_0",
    "lxsdx": "kISA_2_06", "stxsdx": "kISA_2_06",
    "lxsspx": "kISA_2_07", "stxsspx": "kISA_2_07",
    "lxsiwzx": "kISA_2_07", "lxsiwax": "kISA_2_07", "stxsiwx": "kISA_2_07",
}


def feature_of(name):
    if name in FEATURE_BY_NAME:
        return FEATURE_BY_NAME[name]
    if name.startswith("v"):
        return "kAltivec"  # VMX.
    if name.startswith(("xs", "xv", "xx")):
        return "kVSX"
    return "kNone"


def main():
    with open(HEADER) as f:
        text = f.read()

    decls = re.findall(r"ASMJIT_API Error ([A-Za-z_][A-Za-z0-9_]*)\(([^)]*)\)", text)
    names = [n for n, _ in decls if n not in EXCLUDED]
    params = {n: a for n, a in decls if n not in EXCLUDED}

    lines = [
        "// This file is part of AsmJit project <https://asmjit.com>",
        "//",
        "// See <asmjit/core.h> or LICENSE.md for license and copyright information",
        "// SPDX-License-Identifier: Zlib",
        "",
        "// Generated by tools/ppc_instgen.py - do not edit manually.",
        "",
        "#ifndef ASMJIT_PPC_PPCINST_H_INCLUDED",
        "#define ASMJIT_PPC_PPCINST_H_INCLUDED",
        "",
        "ASMJIT_BEGIN_SUB_NAMESPACE(ppc)",
        "",
        "//! Instruction.",
        "//!",
        "//! \\note Only used to hold PPC-specific instruction identifiers.",
        "namespace Inst {",
        "  //! Instruction id.",
        "  enum Id : uint32_t {",
        "    kIdNone = 0,                         //!< Invalid instruction id.",
    ]
    for name in names:
        id_name = f"kId{name[0].upper()}{name[1:]}"
        lines.append(f"    {id_name}, {' ' * (42 - len(id_name))}//!< Instruction '{name}'.")
    lines += [
        "",
        "    _kIdCount",
        "  };",
        "} // {Inst}",
        "",
        "ASMJIT_END_SUB_NAMESPACE",
        "",
        "#endif // ASMJIT_PPC_PPCINST_H_INCLUDED",
        "",
    ]

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines))

    db = [
        "// This file is part of AsmJit project <https://asmjit.com>",
        "//",
        "// See <asmjit/core.h> or LICENSE.md for license and copyright information",
        "// SPDX-License-Identifier: Zlib",
        "",
        "// Generated by tools/ppc_instgen.py - do not edit manually.",
        "",
        "#ifndef ASMJIT_PPC_PPCINSTDB_P_H_INCLUDED",
        "#define ASMJIT_PPC_PPCINSTDB_P_H_INCLUDED",
        "",
        "#include <asmjit/ppc/ppcinst.h>",
        "#include <asmjit/core/cpuinfo.h>",
        "",
        "ASMJIT_BEGIN_SUB_NAMESPACE(ppc)",
        "",
        "namespace Inst {",
        "  //! Maximum number of instruction operands.",
        "  static inline constexpr uint32_t kMaxOperands = 6;",
        "",
        "  //! Operand kind.",
        "  enum class Kind : uint8_t {",
        "    kNone = 0, kGp, kFp, kVec, kMem, kLabel, kImm",
        "  };",
        "",
        "  //! Instruction operand signature.",
        "  struct Signature {",
        "    uint8_t required;",
        "    uint8_t count;",
        "    Kind kinds[kMaxOperands];",
        "  };",
        "",
        "  //! Instruction signatures indexed by Inst::Id.",
        "  static constexpr Signature inst_signatures[_kIdCount] = {",
        "    { 0, 0, { Kind::kNone, Kind::kNone, Kind::kNone, Kind::kNone, Kind::kNone, Kind::kNone } }, // kIdNone",
    ]
    for name in names:
        required, total, kinds = parse_params(params[name])
        kinds += ["kNone"] * (6 - len(kinds))
        db.append(f"    {{ {required}, {total}, {{ {', '.join('Kind::' + k for k in kinds)} }} }}, // {name}")
    db += [
        "  };",
        "",
        "  //! Required feature of each instruction (CpuFeatures::PPC::kNone = none).",
        "  static constexpr CpuFeatures::PPC::Id inst_features[_kIdCount] = {",
        "    CpuFeatures::PPC::kNone, // kIdNone",
    ]
    for name in names:
        db.append(f"    CpuFeatures::PPC::{feature_of(name)}, // {name}")
    db += [
        "  };",
        "} // {Inst}",
        "",
        "ASMJIT_END_SUB_NAMESPACE",
        "",
        "#endif // ASMJIT_PPC_PPCINSTDB_P_H_INCLUDED",
        "",
    ]

    with open(OUTPUT_DB, "w") as f:
        f.write("\n".join(db))

    emitinst = [
        "// This file is part of AsmJit project <https://asmjit.com>",
        "//",
        "// See <asmjit/core.h> or LICENSE.md for license and copyright information",
        "// SPDX-License-Identifier: Zlib",
        "",
        "// Generated by tools/ppc_instgen.py - do not edit manually.",
        "//",
        "// Instruction dispatch cases for Assembler::_emit(), included by",
        "// asmjit/ppc/ppcassembler.cpp. Derived from the same method list that",
        "// produces the instruction ids and the instruction database, so the",
        "// generic emission surface can never drift from the instruction set.",
        "",
    ]
    emitted_cases = 0
    for name in names:
        emitinst.append(gen_emit_inst_case(name, params[name]))
        emitted_cases += 1
    emitinst.append("")

    with open(OUTPUT_EMITINST, "w") as f:
        f.write("\n".join(emitinst))


    print(f"generated {len(names)} instruction ids -> {OUTPUT}, {OUTPUT_DB}")
    print(f"generated {len(names)} emitInst cases -> {OUTPUT_EMITINST}")


# Generic emit (Assembler::_emit) generation.
#
# This section is self-contained: it only needs the assembler method list, so
# it can be kept (and was originally introduced) as an independent block.
# ---------------------------------------------------------------------------

#! Instructions whose VSX register operands also accept FPR operands (both
#! are valid VSRs, and the register allocator mirrors FPR bits to GPRs with
#! `mfvsrd`).
EMIT_VEC_OR_FP = {"mfvsrd", "mfvsrld", "mfvsrwz"}

EMIT_OP_CHECK = {
    "Gp": "opGp(ops[{i}])",
    "Fp": "opFp(ops[{i}])",
    "Vr": "opVec(ops[{i}])",
    "Vsx": "opVec(ops[{i}])",
    "const Mem&": "opMem(ops[{i}])",
    "const Label&": "opLabel(ops[{i}])",
    "int16_t": "opImm(ops[{i}])",
    "uint16_t": "opImm(ops[{i}])",
    "uint8_t": "opImm(ops[{i}])",
    "int32_t": "opImm(ops[{i}])",
    "uint32_t": "opImm(ops[{i}])",
    "int64_t": "opImm(ops[{i}])",
    "uint64_t": "opImm(ops[{i}])",
}

EMIT_OP_CAST = {
    "Gp": "ops[{i}].as<Gp>()",
    "Fp": "ops[{i}].as<Fp>()",
    "Vr": "ops[{i}].as<Vr>()",
    "Vsx": "ops[{i}].as<Vsx>()",
    "const Mem&": "ops[{i}].as<Mem>()",
    "const Label&": "ops[{i}].as<Label>()",
    "int16_t": "immAs<int16_t>(ops[{i}])",
    "uint16_t": "immAs<uint16_t>(ops[{i}])",
    "uint8_t": "immAs<uint8_t>(ops[{i}])",
    "int32_t": "immAs<int32_t>(ops[{i}])",
    "uint32_t": "immAs<uint32_t>(ops[{i}])",
    "int64_t": "immAs<int64_t>(ops[{i}])",
    "uint64_t": "immAs<uint64_t>(ops[{i}])",
}


def emitinst_parse_params(args):
    """Returns [(cpp_type, default_expr)] for the non-bool params of `args`."""
    result = []
    for param in args.split(","):
        param = param.strip()
        if not param:
            continue
        has_default = "=" in param
        lhs = param.split("=", 1)[0].strip()
        default = param.split("=", 1)[1].strip() if has_default else None
        type_name = lhs.rsplit(" ", 1)[0].strip()
        if type_name == "bool":
            continue  # Trailing Rc/Oe flags are not exposed through generic emit().
        result.append((type_name, default))
    return result


def gen_emit_inst_case(name, args):
    """Generates the Assembler::_emit() dispatch case for `name`.

    The case validates the operands against the generated signature and calls
    the dedicated assembler method. Optional trailing immediates (C++ default
    arguments such as `cmpd`'s `bf`) accept a shorter operand list.
    """
    plist = emitinst_parse_params(args)
    required = sum(1 for _, default in plist if default is None)
    total = len(plist)

    checks = [f"op_count < {required}", f"op_count > {total}"]
    for i, (t, default) in enumerate(plist):
        if t == "Vsx" and name in EMIT_VEC_OR_FP:
            check = f"(opFp(ops[{i}]) || opVec(ops[{i}]))"
        else:
            check = EMIT_OP_CHECK[t].format(i=i)
        if i >= required:
            check = f"(op_count > {i} && !{check})"
        else:
            check = f"!{check}"
        checks.append(check)

    args_list = []
    for i, (t, default) in enumerate(plist):
        cast = EMIT_OP_CAST[t].format(i=i)
        if i >= required:
            args_list.append(f"op_count > {i} ? {cast} : {default if default is not None else '0'}")
        else:
            args_list.append(cast)

    id_name = f"kId{name[0].upper()}{name[1:]}"
    cond = " || ".join(checks)
    return "\n".join([
        f"    case Inst::{id_name}:",
        f"      if (ASMJIT_UNLIKELY({cond}))",
        "        return emitInvalidOperand();",
        f"      return asm_.{name}({', '.join(args_list)});",
    ])



if __name__ == "__main__":
    main()
